version: "3.1"
services:
  # Build frontend resources
  frontend:
    tty: false
    build:
      context: .
      dockerfile: ./docker/frontend.docker
    command: yarn run build
    volumes:
      - ./bootstrap-theme/src/main:/build/src/main
      # scope node_modules to the container
      - /build/src/main/frontend/node_modules
      - ./bootstrap-theme/src/main/resources/views/static/adminweb-themes:/build/src/main/resources/META-INF/resources/webjars/ax-bootstrap-theme/0.0.1:delegated
      - ./ax-bootstrap-4-utilities/src/main/resources/:/build/src/main/frontend/webjars
