version: "3.1"
services:
  # Build frontend resources
  frontend:
    tty: false
    build:
      context: .
      dockerfile: ./docker/frontend.docker
    command: sh -c "yarn && yarn run build"
    working_dir: /build/ax-bootstrap-theme/src/main/frontend
    volumes:
      - ./:/build
#       scope node_modules to the container
      - /build/ax-bootstrap-theme/src/main/frontend/node_modules
#      - ./ax-bootstrap-4-utilities/src/main/resources/:/build/src/main/frontend/webjars
