version: "3.1"
services:
  # compiling frontend resources
  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.assets
    image: entity-module-assets:latest
    command: yarn run build
    container_name: entity-module-assets-builder
    volumes:
    - ./entity-module/src/main/frontend:/build
    - ./entity-module/src/main/resources/views/static/entity:/resources/views/static/entity

  # Update frontend resources lockfile
  update-lockfile:
    image: beforeach/node:10
    command: yarn install --modules-folder /node_modules
    container_name: entity-module-update-lockfile
    volumes:
      - ./entity-module/src/main/frontend:/build

#  # executing e2e tests
#  web:
#    ipc: host
#    # TTY doesn't show pretty in bamboo
#    tty: false
#    build:
#      context: .
#      dockerfile: entity-module/src/main/frontend/tests/e2e/web/Dockerfile
#    ports:
#    - "8080:8080"
#    expose:
#    - "8080"
#    #    depends_on:
#    #      - gulp
#    volumes:
#    - ./entity-module-test/target:/web
#    networks:
#      default:
#        aliases:
#        - bootstrapui-test.dev.foreach.be
#  test:
#    ipc: host
#    # TTY doesn't show pretty in bamboo
#    tty: false
#    build:
#      context: .
#      dockerfile: entity-module/src/main/frontend/tests/e2e/tests/Dockerfile
#    depends_on:
#    - web
#    command: bash -c "./wait-for-it.sh -t 360 web:8080 -- run; ./node_modules/.bin/cypress run --project ./cypress --reporter junit --reporter-options mochaFile=cypress/out/test-results.xml; chmod -R 777 ./cypress"
#    links:
#    - web
#    volumes:
#    - ./entity-module/src/main/frontend/tests/e2e/tests:/cypress
#  cleanup:
#    image: busybox:latest
#    command: sh -c "echo Cleanup up /cypress/cypress/out; ls -al /cypress/cypress; rm -rf /cypress/cypress/out"
#    volumes:
#    - ./entity-module/src/main/frontend/tests/e2e/tests:/cypress