version: "3.1"
services:
  # Build frontend resources
  frontend:
    tty: false
    build:
      context: .
      dockerfile: ./docker/frontend.docker
    command: ./build-prod.sh build:webjar
    volumes:
      - ./bootstrap-ui-module-frontend/src/main/frontend:/build/src/main/frontend:cached
      # scope node_modules to the container
      - /build/src/main/frontend/node_modules
      - ./bootstrap-ui-module-frontend/src/main/resources:/build/src/main/resources:delegated
      - ./bootstrap-ui-module-frontend/target:/build/target:delegated

  # Update frontend resources lockfile
  update-lockfile:
    image: node:12.9.1-alpine
    command: yarn install
    container_name: bootstrap-ui-module-update-lockfile
    working_dir: /build
    volumes:
      - ./bootstrap-ui-module-frontend/src/main/frontend:/build
      # scope node_modules to the container
      - /build/node_modules

  # Executing E2E tests
  web:
    ipc: host
    # TTY doesn't show pretty in bamboo
    tty: false
    build:
      context: .
      dockerfile: ./docker/e2e-web.docker
    ports:
      - "8080:8080"
    expose:
      - "8080"
    #    depends_on:
    #      - gulp
    volumes:
      - ./bootstrap-ui-module-test/target:/web
    networks:
      default:
        aliases:
          - bootstrapui-test.dev.foreach.be

  e2e:
    ipc: host
    # TTY doesn't show pretty in bamboo
    tty: false
    build:
      context: .
      dockerfile: ./docker/e2e-tests.docker
    depends_on:
      - web
    command: bash -c "./wait-for-it.sh -t 360 web:8080 -- run; ./node_modules/.bin/cypress run --project ./cypress --reporter junit --reporter-options mochaFile=cypress/out/test-results-[hash].xml; chmod -R 777 ./cypress"
    links:
      - web
    volumes:
      - ./bootstrap-ui-module-frontend/src/main/frontend/test/e2e/tests:/cypress

  cleanup:
    image: busybox:latest
    command: sh -c "echo Cleanup up /cypress/cypress/out; ls -al /cypress/cypress; rm -rf /cypress/cypress/out"
    volumes:
      - ./bootstrap-ui-module/src/main/frontend/tests/e2e/tests:/cypress
