version: "3.1"
services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.assets
    image: bootstrap-ui-module-assets
    command: yarn run build
    container_name: bootstrap-ui-module-assets-builder
    volumes:
    - ./bootstrap-ui-module/src/main/frontend:/build
    - ./bootstrap-ui-module/src/main/resources/views/static/BootstrapUiModule:/resources/views/static/BootstrapUiModule