version: "3.1"
services:
  # Build frontend resources
  frontend:
    tty: false
    build:
      context: .
      dockerfile: ./docker/frontend.docker
    command: sh -c "cd bootstrap-theme/src/main/frontend && yarn && yarn run build && ls -la ../resources/META-INF/resources/webjars/ax-bootstrap-theme/0.0.1"
    working_dir: /build
    volumes:
      - ./:/build
#       scope node_modules to the container
      - /build/bootstrap-theme/src/main/frontend/node_modules
#      - ./ax-bootstrap-4-utilities/src/main/resources/:/build/src/main/frontend/webjars
