version: "3.1"
services:
  # compiling frontend resources
  frontendv2:
    build:
      context: ./bootstrap-ui-module-frontend
      dockerfile: ./Dockerfile
    volumes:
      - ./bootstrap-ui-module/src/main/resources/views/static/BootstrapUiModule:/build/dist
    command: yarn run build
  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.assets
    image: bootstrap-ui-module-assets
    command: yarn run build
    container_name: bootstrap-ui-module-assets-builder
    volumes:
      - ./bootstrap-ui-module/src/main/frontend:/build
      - ./bootstrap-ui-module/src/main/resources/views/static/BootstrapUiModule:/resources/views/static/BootstrapUiModule

  # executing e2e tests
  web:
    ipc: host
    # TTY doesn't show pretty in bamboo
    tty: false
    build:
      context: .
      dockerfile: bootstrap-ui-module/src/main/frontend/tests/e2e/web/Dockerfile
    ports:
      - "8080:8080"
    expose:
      - "8080"
    #    depends_on:
    #      - gulp
    volumes:
      - ./bootstrap-ui-module-test/target:/web
    networks:
      default:
        aliases:
          - bootstrapui-test.dev.foreach.be
  test:
    ipc: host
    # TTY doesn't show pretty in bamboo
    tty: false
    build:
      context: .
      dockerfile: bootstrap-ui-module/src/main/frontend/tests/e2e/tests/Dockerfile
    depends_on:
      - web
    command: bash -c "./wait-for-it.sh -t 360 web:8080 -- run; ./node_modules/.bin/cypress run --project ./cypress --reporter junit --reporter-options mochaFile=cypress/out/test-results-[hash].xml; chmod -R 777 ./cypress"
    links:
      - web
    volumes:
      - ./bootstrap-ui-module/src/main/frontend/tests/e2e/tests:/cypress
  cleanup:
    image: busybox:latest
    command: sh -c "echo Cleanup up /cypress/cypress/out; ls -al /cypress/cypress; rm -rf /cypress/cypress/out"
    volumes:
      - ./bootstrap-ui-module/src/main/frontend/tests/e2e/tests:/cypress
