across:
  development:
    active: true

adminWebModule:
  root-path: /
  login:
    rememberMe:
      key: remember-me
  title: Hello application...
  locale:
    options:
      - 'en_GB'
      - 'nl_BE'
    default-locale: 'nl_BE'

acrossModule:
  AdminWebModule:
    resources: admin-web-module/src/main/resources